services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sales-dashboard-backend
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/doctor-appointment
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy || true && npx prisma generate || true && npx prisma db seed || true && npm run start:dev || true"

  db:
    image: postgres:15
    container_name: sales-dashboard-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
